article/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^$', views.main),
    url(r'^category/(?P<category_id>\d+)/$', views.category, name='category'),
    url(r'^article/(?P<article_id>\d+)/$', views.article, name='article'),
    url(r'^tag/(?P<tag_name>[a-zA-Z0-9+#_]+)/$', views.tag, name='tag'),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

awesome_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from article import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('article.urls')),
]

article/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.


class Categories(models.Model):
    class Meta():
        db_table = 'Categories'
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Articles(models.Model):
    class Meta():
        db_table = 'Articles'
    title = models.CharField(max_length=255)
    text = models.TextField()
    category = models.ForeignKey(Categories)
    image = models.ImageField(upload_to='photos/', default='photos/no-img.jpg')

    def __str__(self):
        return self.title


class Comments(models.Model):
    class Meta():
        db_table = 'Comments'
    comment = models.TextField()
    author = models.CharField(max_length=70, blank=True)
    email = models.EmailField()
    website = models.CharField(max_length=255)
    article = models.ForeignKey(Articles)

    def __str__(self):
        return self.comment


class Tags(models.Model):
    class Meta():
        db_table = 'Tags'
    name = models.CharField(max_length=70)
    article = models.ForeignKey(Articles)

    def __str__(self):
        return self.name

article/forms.py
from models import Comments, Tags
from django import forms
from django.core.exceptions import ValidationError


class CommentsForm(forms.ModelForm):
    comment = forms.CharField(widget=forms.Textarea)
    author = forms.CharField(max_length=70, required=False)
    email = forms.EmailField(required=False)
    website = forms.CharField(max_length=255, required=False)

    class Meta:
        model = Comments
        fields = ('comment', 'author', 'email', 'website')

article/views.py
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext
from annoying.decorators import render_to

from models import Categories, Articles, Comments, Tags
from django.db.models import Count, Avg

from .forms import CommentsForm


# Create your views here.
@render_to('last_posts.html')
def main(request):
    categories = Categories.objects.all()
    articles = Articles.objects.filter().order_by('-id')[:6]. \
        annotate(Count('comments'), Avg('category'))
    return {'categories': categories, 'articles': articles}


@render_to('category.html')
def category(request, category_id):
    category = Categories.objects.get(id=category_id)
    categories = Categories.objects.all()
    articles = Articles.objects.filter(category_id=category_id). \
        order_by('-id').annotate(Count('comments'), Avg('category'))
    return {'categories': categories,
            'category': category,
            'articles': articles}


@render_to('article.html')
def article(request, article_id):
    if request.method == 'POST':
        form = CommentsForm(request.POST)
        if form.is_valid():
            textfield = request.POST.get('comment')
            usrname = request.POST.get('author')
            email = request.POST.get('email')
            website = request.POST.get('website')
            if request.user.is_authenticated():
                Comments.objects.create(
                       comment=textfield,
                       article_id=article_id,
                       author=request.user.username,
                       email=request.user.email,
                       website='www.localhost.com')
            else:
                if not usrname:
                    Comments.objects.create(
                           comment=textfield,
                           article_id=article_id,
                           author='Anonymous',
                           email=email,
                           website=website)
                else:
                    Comments.objects.create(
                           comment=textfield,
                           article_id=article_id,
                           author=usrname,
                           email=email,
                           website=website)
    else:
        form = CommentsForm()
    tags = Tags.objects.filter(article_id=article_id)
    article = Articles.objects.get(id=article_id)
    comments = Comments.objects.filter(article_id=article_id)
    categories = Categories.objects.all()
    return {'categories': categories, 'category': category,
            'article': article, 'comments': comments, 
            'form': form, 'tags': tags}


@render_to('posts_by_tag.html')
def tag(request, tag_name):
    categories = Categories.objects.all()
    article_id = Tags.objects.filter(name=tag_name)
    obj = [] 
    for a in article_id:
        obj.append(Articles.objects.filter(id=a.article_id).order_by('-id')[:6]. \
            annotate(Count('comments'), Avg('category')))
    return {'categories': categories, 'articles': obj}

article/templates/article.html
{% extends 'index.html' %}
{% load get_info  staticfiles %}
{% block category %}
	<div id="post">
		<h1>{{ article.title }}</h1>
		{% for tag in tags %}
		    <a href="{% url 'tag' tag.name %}">{{ tag.name }}</a>
		{% endfor %}
		<br>
		<img src="{{ MEDIA_URL }}{{ article.image.url }}" class="article_img" />
		<p>
		   {{ article.text }}
		</p>
		<hr>
		<h1>Comments:</h1>
		  {% for comment in comments %}
		    <div class="comment">
		      {% autoescape off %} 
		        {% if comment.author == 'admin' %}
			  {% render_avatar comment.author %}
 		        {% elif comment.author == 'Anonymous' %}
			  {% render_avatar comment.author %}
		        {% else %}
			  {% render_avatar 'user' %}
		        {% endif %}
		      {% endautoescape %}
		      <p>{{ comment.author }} / {{ comment.email }} / {{ comment.website }}</p>
		      <p>{{ comment.comment }}</p>
		    </div>
		  {% endfor %}
		<hr>
		<form class="form-horizontal" role="form" method="POST">
			{% csrf_token %}
			{{ form.non_field_errors }}
			<div class="form-group">
		          <div class="col-sm-12">
			    {{ form.comment.errors }}
			    {{ form.comment }}
		          </div>
		        </div>
			{% if not request.user.is_authenticated %}
				<div class="form-group">
				  <div class="col-sm-12">
				    {{ form.author.errors }}
				    {{ form.author }}
				  </div>
				</div>
				<div class="form-group">
				  <div class="col-sm-12">
				    {{ form.email.errors }}
				    {{ form.email }}<br>
				  </div>
				</div>
				<div class="form-group">
				  <div class="col-sm-12">
				    {{ form.website.errors }}
				    {{ form.website }}
				  </div>
				</div>
			{% endif %}
			<div class="col s6">
			  <div class="form-group">
				<input type="submit" onclick="validate(event, this.form)" class="btn btn-default" value="Leave comment" style="width:130px;">
			  </div>
			</div>
		    </div>
		</form>
	</div>
{% endblock %}

article/templates/category.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block category %}
	<div id="categ">
		<h1>{{ category.name }}</h1>
		{% for article in articles %}
			<div class="article">
				<a href="{% url 'article' article.id %}"><h4>{{ article.title }}</h4></a>
				<p>
				   {{ article.text }}
				</p>
				<img src="/static/img/comment.png" height="30" width="30">{{ article.comments__count }}
				<a href="{% url 'category' article.category.id %}">#{{ article.category.name }}#</a>
			</div>
		{% endfor %}
	</div>
{% endblock %}

article/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="application/x-www-form-urlencoded">
    <title>Awesome Blog</title>
    <link type="text/css" rel="stylesheet" href="{% static 'css/main.css' %}" />
    <script src="/static/js/main.js"></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script>
	$(document).ready(function(){
	    $("#id_comment").addClass("form-control");
	    $("input").addClass("form-control");
	});
    </script>
  </head>
  <body>
	<div id="wrap">
		<header>
			<a href="/"><img src="/static/img/blog.png" height="70" width="110"></a>
			<p>< Welcome to our awesome blog /></p>
		</header>
		<div id="categories">
		    {% for category in categories %}
			<a class="category" href="{% url 'category' category.id %}">{{ category.name }}</a>
		    {% endfor %}		
		</div>	
		<div id="articles">
			{% block last_posts %}{% endblock %}
			{% block category %}{% endblock %}
			{% block article %}{% endblock %}
		</div>
			
	</div>  
  </body>
</html>

article/templates/last_posts.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block last_posts %}
    <h1>Recently posted articles</h1>
    {% for article in articles %}
	<div class="article">
		<a href="{% url 'article' article.id %}"><h4>{{ article.title }}</h4></a>
		<p>
		   {{ article.text }}
		</p>
		<img src="/static/img/comment.png" height="30" width="30">{{ article.comments__count }}
		<a href="{% url 'category' article.category.id %}">#{{ article.category.name }}#</a>
	</div>
    {% endfor %}

{% endblock %}

article/templates/posts_by_tag.html
{% extends 'index.html' %}
{% load staticfiles %}
{% block last_posts %}
    <h1>Recently posted articles</h1>
    {% for article in articles %}
        {% for art in article %}
	<div class="article">
		<a href="{% url 'article' art.id %}"><h4>{{ art.title }}</h4></a>
		<p>
		   {{ art.text }}
		</p>
		<img src="/static/img/comment.png" height="30" width="30">{{ art.comments__count }}
		<a href="{% url 'category' art.category.id %}">#{{ art.category.name }}#</a>
	</div>
        {% endfor %}
    {% endfor %}

{% endblock %}